library(dplyr)
library(ggplot2)
JDG <- read.csv("C:/Users/Lab User/Dropbox/Andrew Z/Ridgetop 1995-2019 Refined.txt", sep = ",", header = TRUE)
JDG1 <- select(JDG, ï..AvgTEMP_C, Month, Day, Year)
JDG2 <- na.omit(JDG1)
JDG3 <- group_by(JDG2, Day, Year)
JDG4 <- summarize(JDG3, dailymean = mean(ï..AvgTEMP_C))
